from enum import Enum


class RuleType(Enum):
  CLOSED_RULE = 1
  EXISTS_TRUE_RULE = 2
  EXISTS_FALSE_RULE = 3
  OR_TRUE_RULE = 4
  OR_FALSE_RULE = 5
  AND_TRUE_RULE = 6
  AND_FALSE_RULE = 7
  IMPLICATION_TRUE_RULE = 8
  IMPLICATION_FALSE_RULE = 9
  FOR_ALL_TRUE_RULE = 10
  FOR_ALL_FALSE_RULE = 11
  NEGATION_RULE = 12